---
- name: "Install dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pkcon install -y {{ item }} | true"
  loop: "{{ APP_DEPENDENCIES }}"
- name: "Install python dependencies: {{ APP_DEPENDENCIES | join(' ') }}"
  shell: "pip install {{ item }} | true"
  loop: "{{ PYTHON_DEPENDENCIES }}"
- name: "Create the directory {{ APP_SRC }}"
  ansible.builtin.file:
    path: "{{ APP_SRC }}"
    state: directory
- name: "Check for the README file {{ APP_README }}"
  stat:
    path: "{{ APP_README }}"
  register: APP_README_PATH
- name: "Clone the {{ APP_REPO }} source code into {{ APP_SRC }}"
  git:
    repo: "{{ APP_REPO }}"
    dest: "{{ APP_SRC }}"
    version: "{{ APP_TAG }}"
  when: not APP_README_PATH.stat.exists
  ignore_errors: true
- name: "Create the build directory {{ APP_SRC }}/build"
  file:
    name: "{{ APP_SRC }}/build"
    state: directory
- name: "Run the python setup.py build in {{ APP_SRC }}"
  shell:
    cmd: python3 setup.py build
    chdir: "{{ APP_SRC }}"
- name: "Run the python setup.py install in {{ APP_SRC }}"
  shell:
    cmd: python3 setup.py install -f --user
    chdir: "{{ APP_SRC }}"
- name: "Run the pip install . in {{ APP_SRC }}"
  shell:
    cmd: pip install .
    chdir: "{{ APP_SRC }}"
- name: "Create the launcher {{ APP_DESKTOP }}"
  template:
    src: app.desktop
    dest: "{{ APP_DESKTOP }}"

